script: bash ./deploy.sh
language: node_js
node_js:
  - '0.12'
env:
  global:
  - GH_REF: github.com/mushishi78/two-takes.git
  - secure:  "H0ZkVujS+5IFaJTS8U3N9cX8pIIY/T+O3Yia69G/IzY+0jmpk6abkZZDqQoMSdz4Z6OzKQZ0+RHfLI0N7Q4vbTEFZnY14BCSLmbxsF07AyPr6NTLpc5Uk1QAyM82tbZhpq4sxH74rBKtCuZjOJV5Gl5OUxu/X7lZRY+R2qsTxsm+EupR2lUvRvEWQuKGZzQaIPhRMzg6WZroC2gDO7+GYCM1YiAYp3O2rjACLtLXNKuZaYdTtgMQ8KnUo0ZghdMIxFN8vh0Nw8hbe07dk/sih/S6hfzUtGcTtSLqos+InRqhLrvz+VAe6lpnNapHv837jE4iZSuzhYSeLwT33aEhiNzqj3sYZWEoqYO6Bk9CPjOplo82a67Tj/3308C6zKpBlVi2vj0drlDlwqNP0TqKxt+9EJqQ6n0cdhsP2mMNGrywVNN//JlrpOSjcAg/p0QMX50KzZv7k1HwuypjHtFauOuzebnafazzV8xHrwIgITytqXg2CsnEuqVhbs9wRac/r/JZ2CKEDgMVkT0j6FVb8oP0T2eozZqzSpJ/NidssgR8OJ0QjqRh9MzQ93BlhcE0tXRmPVyJQ2dJAct6oeXs6N4/QoZxGNJt64QEMzZEkTXWe/KcajabThfA4Ar67x62mvYBN3zgqdlKurC7Bw0tFXCBxMaMKsRlCi62gmQJBGc="
